{% set name = "cmap" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmap-{{ version }}.tar.gz
  sha256: c4aca909bdd65c76ab59d0c875e8c3fc4b1252076c5ea4ef37fbb03d9784980d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - numpy

test:
  imports:
    - cmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/cmap
  summary: Scientific colormaps for python, with only numpy dependency
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE/LICENSE
    - LICENSE/LICENSE_YORICK
    - LICENSE/LICENSE_WISTIA
    - LICENSE/LICENSE_GLASBEY
    - LICENSE/LICENSE_CVIDIS
    - LICENSE/LICENSE_CRAMERI
    - LICENSE/LICENSE_COLORCET
    - LICENSE/LICENSE_COLORBREWER
    - LICENSE/LICENSE_CMOCEAN
  doc_url: https://cmap-docs.rtfd.io
  dev_url: https://github.com/tlambert03/cmap

extra:
  recipe-maintainers:
    - tlambert03
