{% set name = "cmap" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cmap-{{ version }}.tar.gz
  sha256: a511cb0ab349d2ecb7c03f0bb050f5feff5e6fc18d1a503d930b01e3fd80459e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - cmap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tlambert03/cmap
  summary: Scientific colormaps for python, with only numpy dependency
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE/LICENSE
    - LICENSE/LICENSE_YORICK
    - LICENSE/LICENSE_WISTIA
    - LICENSE/LICENSE_GLASBEY
    - LICENSE/LICENSE_CVIDIS
    - LICENSE/LICENSE_CRAMERI
    - LICENSE/LICENSE_COLORCET
    - LICENSE/LICENSE_COLORBREWER
    - LICENSE/LICENSE_CMOCEAN
  doc_url: https://cmap-docs.rtfd.io
  dev_url: https://github.com/tlambert03/cmap

extra:
  recipe-maintainers:
    - tlambert03
